name: Run Job Scraper Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright dependencies
      run: |
        playwright install chromium

    - name: Wait before starting scraper (Cloudflare mitigation)
      run: sleep 5

    - name: Run job scraper
      env:
        DB_PATH: ./data/job_data.db
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        NO_EXP_TELEGRAM_TOKEN: ${{ secrets.NO_EXP_TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        NO_EXP_CHAT_ID: ${{ secrets.NO_EXP_CHAT_ID }}
      run: python run_scraper.py

    - name: Commit and push database changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./data/job_data.db
        git commit -m "Update database with new job listings" || echo "No changes to commit"
        git push