name: Run Job Scraper Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Дозволяє вручну запускати робочий процес

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Compute cache key
      id: cache-key
      run: echo "key=csv-cache-${{ runner.os }}-$(find ./csv_files -type f -exec sha256sum {} + | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Restore cached CSV files
      uses: actions/cache@v3
      with:
        path: ./csv_files
        key: ${{ steps.cache-key.outputs.key }}
        restore-keys: csv-cache-${{ runner.os }}-

    - name: Debug CSV files (Before Script)
      run: |
        echo "CSV files before script execution:"
        ls -l ./csv_files || echo "No CSV files found"

    - name: Ensure CSV directory exists
      run: mkdir -p ./csv_files

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run job scraper
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        NO_EXP_TELEGRAM_TOKEN: ${{ secrets.NO_EXP_TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        NO_EXP_CHAT_ID: ${{ secrets.NO_EXP_CHAT_ID }}
      run: python main.py

    - name: Debug CSV files (After Script)
      run: |
        echo "CSV files after script execution:"
        ls -l ./csv_files || echo "No CSV files generated"

    - name: Update cache with new CSV files
      uses: actions/cache@v3
      with:
        path: ./csv_files
        key: ${{ steps.cache-key.outputs.key }}
