name: Run Job Scraper Hourly

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual runs

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Download CSV files
      uses: actions/download-artifact@v2
      with:
        name: csv-files
        path: ./csv_files

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run job scraper
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py

    - name: Upload CSV files
      uses: actions/upload-artifact@v2
      with:
        name: csv-files
        path: ./csv_files
